version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@17
  pre_build:
    commands:
      - npm install
  build:
    commands:
      #- echo Build error simulation #빌드 강제로 오류나게해서 종료하게
      #- exit 1
      - ng build -c production
      - echo "Build completed."
    finally:
      - echo This is the finally block execution!
artifacts:
  files:
    - 'dist/my-angular-project/**/*'
    - appspec.yml
    - 'deploy-scripts/**/*'